FROM mcr.microsoft.com/dotnet/sdk:7.0-bullseye-slim-arm64v8 AS build
WORKDIR /app
COPY . .

RUN dotnet publish Client/Client.csproj -c Release -o client-release

FROM mcr.microsoft.com/dotnet/aspnet:7.0.0-rc.1-bullseye-slim-amd64

WORKDIR /client
COPY --from=build /app/client-release .

ENTRYPOINT [ "dotnet", "/client/Client.dll" ]