FROM mcr.microsoft.com/dotnet/sdk:7.0-bullseye-slim-arm64v8 AS build
WORKDIR /app

COPY . .
RUN ls -a

RUN dotnet publish Api/Api.csproj -c Release -o api-release

FROM mcr.microsoft.com/dotnet/aspnet:7.0.0-rc.1-bullseye-slim-amd64
WORKDIR /api
COPY --from=build /app/api-release .

ENTRYPOINT [ "dotnet", "/api/Api.dll" ]